{
  "openapi": "3.0.3",
  "info": {
    "title": "NFT Service APIs",
    "description": "",
    "license": {
      "name": ""
    },
    "version": "2.0"
  },
  "servers": [
    {
      "url": "https://api.bitski.com"
    }
  ],
  "paths": {
    "/contracts/{contract_id}/metadata": {
      "get": {
        "tags": [
          "Minting"
        ],
        "summary": "Get contract metadata",
        "description": "Get contract metadata",
        "operationId": "contract_metadata"
      }
    },
    "/contracts/{contract_id}/token-metadata/{token_id}": {
      "get": {
        "tags": [
          "Minting"
        ],
        "summary": "Get token metadata",
        "description": "Get token metadata",
        "operationId": "token_metadata"
      }
    },
    "/v1/apps/{app_id}/contracts": {
      "get": {
        "tags": [
          "Minting"
        ],
        "summary": "List all your contracts",
        "description": "List all your contracts",
        "operationId": "list_contracts",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Minting"
        ],
        "summary": "Creates the draft of a contract without deploying it.",
        "description": "Creates the draft of a contract without deploying it.\n\nFor external contract types like ZORA, \"create\" just imports it - you never will deploy it since its already deployed.",
        "operationId": "create_contract",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/contracts/{contract_id}": {
      "get": {
        "tags": [
          "Minting"
        ],
        "summary": "Get details about a contract",
        "description": "Get details about a contract",
        "operationId": "get_contract",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Minting"
        ],
        "summary": "Update a contract",
        "description": "Update a contract",
        "operationId": "patch_contract",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/fulfillments": {
      "post": {
        "tags": [
          "Commerce"
        ],
        "summary": "Create a fulfillment for an order",
        "description": "Create a fulfillment for an order",
        "operationId": "create_fulfillment"
      }
    },
    "/v1/apps/{app_id}/fulfillments/{fulfillment_id}": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "Get fulfillment details",
        "description": "Get fulfillment details",
        "operationId": "get_fulfillment"
      },
      "patch": {
        "tags": [
          "Commerce"
        ],
        "summary": "Update fulfillment status",
        "description": "Update fulfillment status",
        "operationId": "patch_fulfillment"
      }
    },
    "/v1/apps/{app_id}/gates": {
      "get": {
        "tags": [
          "Token Gating"
        ],
        "summary": "List gates for an app",
        "description": "List gates for an app",
        "operationId": "list",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Token Gating"
        ],
        "summary": "Create a gate that can be later applied to a sale or droplink.",
        "description": "Create a gate that can be later applied to a sale or droplink.",
        "operationId": "create",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/gates/{gate_id}": {
      "get": {
        "tags": [
          "Token Gating"
        ],
        "summary": "Gets details about a gate.",
        "description": "Gets details about a gate.",
        "operationId": "get",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Token Gating"
        ],
        "summary": "Update a gate.",
        "description": "Update a gate.",
        "operationId": "update",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/token-templates": {
      "get": {
        "tags": [
          "Minting"
        ],
        "operationId": "get_token_templates",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Minting"
        ],
        "operationId": "create_token_template",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/token-templates/{token_template_id}": {
      "get": {
        "tags": [
          "Minting"
        ],
        "operationId": "token_template",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Minting"
        ],
        "operationId": "update_token_template",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/tokens": {
      "get": {
        "tags": [
          "Minting"
        ],
        "summary": "List tokens",
        "description": "List tokens",
        "operationId": "get_tokens",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Minting"
        ],
        "summary": "Create a new token",
        "description": "Create a new token",
        "operationId": "create_token",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/apps/{app_id}/tokens/{token_id}": {
      "get": {
        "tags": [
          "Minting"
        ],
        "summary": "Get token details",
        "description": "Get token details",
        "operationId": "get_token",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Minting"
        ],
        "summary": "Update token details",
        "description": "Update token details",
        "operationId": "update_token",
        "security": [
          {
            "oauth2": [
              "apps"
            ]
          }
        ]
      }
    },
    "/v1/auctions/{auction_id}": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "Get details about an auction",
        "description": "Get details about an auction",
        "operationId": "get_auction_info"
      }
    },
    "/v1/claim-codes/claims/unclaimed": {
      "get": {
        "tags": [
          "Droplinks"
        ],
        "summary": "Get unclaimed codes.",
        "description": "Get unclaimed codes.\n\nReturns available claim codes matching the passed in ids that the current\nuser has not yet claimed.",
        "operationId": "get_unclaimed_codes",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v1/claim-codes/{claim_code_id_or_code}": {
      "get": {
        "tags": [
          "Droplinks"
        ],
        "summary": "Get a claim code by its id or code",
        "description": "Get a claim code by its id or code",
        "operationId": "get"
      }
    },
    "/v1/claims": {
      "post": {
        "tags": [
          "Droplinks"
        ],
        "operationId": "create",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v1/gates/check": {
      "get": {
        "tags": [
          "Token Gating"
        ],
        "operationId": "check"
      }
    },
    "/v1/orders": {
      "post": {
        "tags": [
          "Commerce"
        ],
        "summary": "Create a new pending order.",
        "description": "Create a new pending order.\n\nNo payment or fulfillment is completed on create order.\n\nA payment intent is created and associated to the order to track sales that\nmay not be completed.",
        "operationId": "create_order",
        "security": [
          {
            "oauth2": [
              "commerce"
            ]
          }
        ]
      }
    },
    "/v1/orders/{order_id}": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "Get details for an existing order.",
        "description": "Get details for an existing order.",
        "operationId": "get_order",
        "security": [
          {
            "oauth2": [
              "commerce"
            ]
          }
        ]
      }
    },
    "/v1/orders/{order_id}/payments/{payment_id}": {
      "patch": {
        "tags": [
          "Commerce"
        ],
        "summary": "Update a payment for an order.",
        "description": "Update a payment for an order.\n\nAttempts to process the associated payment.\n\nIf successful, inventory is reserved and fulfillment begins.",
        "operationId": "patch_order_payment",
        "security": [
          {
            "oauth2": [
              "commerce"
            ]
          }
        ]
      }
    },
    "/v1/products": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "Filter products by store",
        "description": "Filter products by store",
        "operationId": "list_products"
      }
    },
    "/v1/products/{product_id}": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "Get product details",
        "description": "Get product details",
        "operationId": "get_product"
      }
    },
    "/v1/stores/{store_id}": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "Get public facing storefront details",
        "description": "Get public facing storefront details",
        "operationId": "store_public"
      }
    },
    "/v1/users/{user_id}/payment-methods": {
      "get": {
        "tags": [
          "Commerce"
        ],
        "summary": "List current user's payment methods",
        "description": "List current user's payment methods",
        "operationId": "list_payment_methods",
        "security": [
          {
            "oauth2": [
              "commerce"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Commerce"
        ],
        "summary": "Add a new payment method",
        "description": "Add a new payment method",
        "operationId": "add_payment_method",
        "security": [
          {
            "oauth2": [
              "commerce"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://account.bitski.com/oauth2/token",
            "scopes": {
              "apps": "manage my applications"
            }
          }
        },
        "description": "Client credentials"
      }
    }
  }
}